<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        // All menu items from the database
        DB::table('menus')->insert([
            [
                'id' => 5,
                'category_id' => 2,
                'subcategory_id' => 2,
                'name' => 'THAI CHICKEN CASHEW NUT SALAD',
                'details' => 'Warm fried cube cut chicken, roasted cashew nut, tomato, onion, coriander & spicy sauce',
                'price' => 670.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'category_id' => 2,
                'subcategory_id' => 2,
                'name' => 'THAI GRILLED CHICKEN SALAD',
                'details' => 'Grilled boneless chicken, carrot, coriander, onion, tomato & spices',
                'price' => 655.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'category_id' => 2,
                'subcategory_id' => 2,
                'name' => 'THAI SHRIMPS SALAD',
                'details' => 'Shrimp, onion, lemon grass, ginger, red chili flakes & roasted ground rice',
                'price' => 775.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'subcategory_id' => 2,
                'name' => 'Classic Prawn Cocktail',
                'details' => 'Minced Tuna fish cooked with spices, egg, flour and served.',
                'price' => 775.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'category_id' => 2,
                'subcategory_id' => 2,
                'name' => 'THAI SHRIMPS ROLL',
                'details' => 'Crispy wrap filled with spiced shrimp',
                'price' => 775.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'category_id' => 4,
                'subcategory_id' => 4,
                'name' => 'THAI MIXED VEGETABLE WITH CHICKEN OR PRAWN',
                'details' => 'Seasonal mixed vegetable cooked with chicken slices & prawn served with capsicum, brocoli and so more.',
                'price' => 610.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'category_id' => 4,
                'subcategory_id' => 4,
                'name' => 'THAI MIXED VEGETABLE',
                'details' => 'Sauté mixed seasonal vegetable cooked with mushroom & baby corn',
                'price' => 610.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'category_id' => 4,
                'subcategory_id' => 4,
                'name' => 'PRAWN WITH VEGETABLE',
                'details' => 'Seasonal fresh vegetable prepared with prawn and regular vegetables',
                'price' => 580.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'category_id' => 4,
                'subcategory_id' => 4,
                'name' => 'STEAMED BROCCOLI',
                'details' => 'Steamed broccoli with butter & garlic sauté for healthy eater serve with butter and pepper and white sauce.',
                'price' => 580.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'category_id' => 4,
                'subcategory_id' => 4,
                'name' => 'FISH WITH VEGETABLE',
                'details' => 'Seasonal fresh vegetable with sliced fish. Sauté mixed seasonal vegetable cooked with mushroom & baby corn',
                'price' => 555.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'category_id' => 4,
                'subcategory_id' => 3,
                'name' => 'THAI FRIED RED SNAPPER',
                'details' => 'Fried red snapper prepared with capsicum, carrot, onion leaves & hot chili sauce.',
                'price' => 1800.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'category_id' => 4,
                'subcategory_id' => 3,
                'name' => 'CHAR GRILLED KING FISH',
                'details' => 'Fried red snapper prepared with capsicum, carrot, onion leaves & hot chili sauce.',
                'price' => 920.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'category_id' => 4,
                'subcategory_id' => 3,
                'name' => 'SLICED FISH WITH MUSHROOM',
                'details' => 'Sliced sea fish prepared with capsicum, onion, mushroom, & ginger.',
                'price' => 995.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'category_id' => 4,
                'subcategory_id' => 3,
                'name' => 'FRIED FISH & OYSTER SAUCE',
                'details' => 'Battered fish cooked with garlic & oyster sauce.',
                'price' => 865.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'category_id' => 4,
                'subcategory_id' => 3,
                'name' => 'Garlic Butter Cod',
                'details' => 'Garlic Butter Cod with Lemon Asparagus Skillet – Healthy, tasty, simple and quick to cook.',
                'price' => 1200.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'category_id' => 4,
                'subcategory_id' => 5,
                'name' => 'TOYO FRIED RICE',
                'details' => 'The toyo or soy sauce fried rice that you would want to try, with ingredients that are easily available.',
                'price' => 810.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'category_id' => 4,
                'subcategory_id' => 5,
                'name' => 'EGG FRIED RICE',
                'details' => 'The toyo or soy sauce fried rice that you would want to try, served with egg and vegetables.',
                'price' => 350.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'category_id' => 4,
                'subcategory_id' => 5,
                'name' => 'SPACIAL EGG FRIED RICE',
                'details' => 'Minced Tuna fish cooked with spices, egg, flour and served with fried rice.',
                'price' => 650.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'category_id' => 4,
                'subcategory_id' => 5,
                'name' => 'THAI SPECIAL FRIED RICE',
                'details' => 'Aromatic rice prepared with sliced chicken, prawn, egg, vegetable, butter oil & sauce.',
                'price' => 550.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'category_id' => 4,
                'subcategory_id' => 5,
                'name' => 'AMERICAN FRIED RICE',
                'details' => 'Special rice & cashew nut cooked with butter, sliced chicken, raisin & spicy sauce.',
                'price' => 655.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'category_id' => 4,
                'subcategory_id' => 5,
                'name' => 'THAI VEGETABLE FRIED RICE',
                'details' => 'Spiced mixed rice cooked with seasonal vegetable & butter oil.',
                'price' => 525.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'category_id' => 2,
                'subcategory_id' => 2,
                'name' => 'Shrimps Orange & Apple Salad',
                'details' => 'Shrimp, onion, lemon grass, ginger, red chili flakes & roasted ground rice',
                'price' => 685.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'category_id' => 1,
                'subcategory_id' => 1,
                'name' => 'CHICKEN VEGETABLE SOUP',
                'details' => 'Sliced chicken prepared with seasonal mixed vegetable.',
                'price' => 540.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'category_id' => 1,
                'subcategory_id' => 1,
                'name' => 'CHICKEN CORN SOUP',
                'details' => 'Mild taste soup cooked with minced chicken, sweet corn & egg.',
                'price' => 550.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'category_id' => 1,
                'subcategory_id' => 1,
                'name' => 'SPECIAL THAI SOUP THICK',
                'details' => 'Sliced chicken & prawn cooked with mushroom, fried onion and chili tomato puree',
                'price' => 735.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'category_id' => 1,
                'subcategory_id' => 1,
                'name' => 'STEAMBOAT SOUP',
                'details' => 'Boneless sliced chicken, prawn, sea fish, and egg boiled with vermeil noodles & seasonal veggies',
                'price' => 1760.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'category_id' => 1,
                'subcategory_id' => 1,
                'name' => 'CHICKEN NOODLE SOUP',
                'details' => 'Sliced chicken & noodles prepared with saucy vegetable.',
                'price' => 665.00,
                'quantity' => 20,
                'discount' => 0,
                'active' => 1,
                'status' => 1,
                'featured' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
